---
title: A historical analysis of the evolution of active travel behaviour in Canada
author:
  - name: Alice Anonymous
    email: alice@example.com
    affiliation: Some Institute of Technology
    correspondingauthor: true
  - name: Bob Security
    email: bob@example.com
    affiliation: Some Institute of Technology
  - name: Cat Memes
    email: cat@example.com
    affiliation: Some Institute of Technology
address:
  - code: Some Institute of Technology
    organization: Big Wig University
    addressline: 1 main street
    city: Gotham
    state: State
    postcode: 123456
    country: United States
journal: "Journal of Transport Geography"
date: "`r Sys.Date()`"
linenumbers: false
numbersections: false
bibliography: mybibfile2
classoption: preprint, 3p, authoryear # remove authoryear is not using `elsarticle-harv`
# Use a CSL with `citation_package = "default"`
# csl: https://www.zotero.org/styles/elsevier-harvard
output: 
  rticles::elsevier_article:
    keep_tex: true
    citation_package: natbib
header-includes:
- \renewcommand{\abstractname}{}
- \renewenvironment{abstract}{}{}
- \usepackage[makeroom]{cancel}
---

```{r install-activeCA, include = FALSE}
# install.packages("pak")
# pak::pak("dias-bruno/ActiveCA")
opts <- options(knitr.kable.NA = "")

knitr::knit_hooks$set(inline = function(x) {
   if (is.numeric(x)) {
     format(x, big.mark = ",", scientific = TRUE)
   } else {
     x
   }
 })


rm(list=ls())
```

```{r load-packages, include=FALSE, cache=FALSE}
# Load packages
library(ActiveCA)
library(here)
library(dplyr)
library(tidyr)
library(ggplot2)
library(kableExtra)
library(reshape2)
library(rlang)
library(scales)
library(gridExtra)
library(ggpubr)
library(grid)
library(stats)
library(Hmisc)
library(stringr)
library(patchwork)
```

```{r load-data, include = FALSE}
# Load data
data(gss_impedances)
data(gss_episodes)
data(gss_main_1992)
data(gss_main_1998)
data(gss_main_2005)
data(gss_main_2010)
data(gss_main_2015)
data(gss_main_2022)
```

```{r renaming-destinations, echo=FALSE, cache=FALSE, include=FALSE}
# Filtering episodes and impedances functions 
gss_episodes <- gss_episodes %>%
  filter(YEAR > 1986)
  
gss_impedances <- gss_impedances %>%
  filter(YEAR > 1986)

# Renaming 'dest_label' and 'orig_label' values to reduce table space
gss_impedances_renamed <- gss_impedances %>%
  mutate(dest_label = case_when(
    dest_label == "Grocery store, other stores or mall" ~ "Grocery store",
    dest_label == "Restaurant, bar or club" ~ "Restaurant",
    dest_label == "Sports centre, field or arena" ~ "Sport area",
    dest_label == "Medical, dental or other health clinic" ~ "Health clinic",
    dest_label == "In the neighbourhood" ~ "Neighbourhood",
    dest_label == "Library, museum or theatre" ~ "Cultural venues",
    TRUE ~ dest_label  # Keep all other values as they are
  ), 
  orig_label = case_when(
    orig_label == "Grocery store, other stores or mall" ~ "Grocery store",
    orig_label == "Restaurant, bar or club" ~ "Restaurant",
    orig_label == "Sports centre, field or arena" ~ "Sport area",
    orig_label == "Medical, dental or other health clinic" ~ "Health clinic",
    orig_label == "In the neighbourhood" ~ "Neighbourhood",
    orig_label == "Library, museum or theatre" ~ "Cultural venues",
    TRUE ~ orig_label))

# Renaming 'dest_label' and 'orig_label' values to reduce table space
gss_episodes_renamed <- gss_episodes %>%
  mutate(dest_label = case_when(
    dest_label == "Grocery store, other stores or mall" ~ "Grocery store",
    dest_label == "Restaurant, bar or club" ~ "Restaurant",
    dest_label == "Sports centre, field or arena" ~ "Sport area",
    dest_label == "Medical, dental or other health clinic" ~ "Health clinic",
    dest_label == "In the neighbourhood" ~ "Neighbourhood",
    dest_label == "Library, museum or theatre" ~ "Cultural venues",
    TRUE ~ dest_label  # Keep all other values as they are
  ), 
  orig_label = case_when(
    orig_label == "Grocery store, other stores or mall" ~ "Grocery store",
    orig_label == "Restaurant, bar or club" ~ "Restaurant",
    orig_label == "Sports centre, field or arena" ~ "Sport area",
    orig_label == "Medical, dental or other health clinic" ~ "Health clinic",
    orig_label == "In the neighbourhood" ~ "Neighbourhood",
    orig_label == "Library, museum or theatre" ~ "Cultural venues",
    TRUE ~ orig_label))
```

# Appendix A {.unnumbered}

```{r kruskal-walking, include = FALSE, warning= FALSE, cache=TRUE}
result_kw <- data.frame()
anos_possiveis <- c("1992", "1998", "2005", "2010", "2015", "2022")
result_pw <- data.frame(matrix(ncol = length(anos_possiveis) + 2, nrow = 0))
colnames(result_pw) <- c(anos_possiveis, "Mode", "Destination")

for(mode in unique(gss_impedances_renamed$MODE)){
  
  for(destino in unique(gss_impedances_renamed[gss_impedances_renamed$MODE == mode, ]$dest_label)){
    
    subset <- gss_impedances_renamed[gss_impedances_renamed$MODE == mode & gss_impedances_renamed$dest_label == destino, ]
    
    if(length(unique(subset$YEAR)) > 1){
      
    subset <- subset %>% 
      uncount(weights = round(WGHT_EPI))

    kw <- kruskal.test(DURATION ~ YEAR, data = subset)
    
    pv_analise <- ifelse(kw$p.value <= 0.05, 'Significant', 'Not significant')
    
    kw_df <- data.frame("Mode" = mode, "Destination" = destino, "KWpvalue" = kw$p.value, "pvalue" = pv_analise)
    
    result_kw <- rbind(result_kw, kw_df)  
    
    if(kw$p.value <= 0.05){
      
      pw <- pairwise.wilcox.test(subset$DURATION, subset$YEAR, p.adjust.method = "bonferroni")
      
      pf_df <- as.data.frame(pw$p.value)

      for (ano in anos_possiveis) {
    if (!(ano %in% colnames(pf_df))) {
      pf_df[[ano]] <- NA  
    }
  }
  
  pf_df <- pf_df[, anos_possiveis, drop = FALSE]
  
  pf_df$Mode <- mode
  pf_df$Destination <- destino
  
  
  result_pw <- rbind(result_pw, pf_df)
    }
      
    }
  }
}

result_pw$Year <- substr(rownames(result_pw), 1, 4)
rownames(result_pw) <- NULL

result_pw_style <- result_pw %>%
  filter(rowSums(select(., `1992`:`2022`) <= 0.05, na.rm = TRUE) > 0)

result_pw_style <- result_pw_style[, colSums(!is.na(result_pw_style)) > 0]

result_pw_style <- result_pw_style[,c("Mode","Destination","Year","1992","1998","2005","2010","2015")]

# result_pw_style <- result_pw_style %>%
#   mutate(across(where(is.numeric), ~ ifelse(. > 0.05, NA, .)))

# result_pw_style <- result_pw_style %>%
#   mutate(across(where(is.numeric), ~ sprintf("%.2e", .x)))

result_pw_style <- result_pw_style %>%
  mutate(across(all_of(c("1992","1998","2005","2010","2015")),
                ~ ifelse(is.na(.x), "", formatC(.x, format = "e", digits = 2))))

table_stats <- result_pw_style %>%
  kable(format = "latex",
        booktabs = TRUE,
        longtable = TRUE,
        caption = paste0("\\label{tab:result-stats}P-values of the pairwise Wilcoxon test.")) %>% 
  kable_styling(full_width = FALSE, 
                latex_options = c("scale_down"),
                font_size = 8) %>%
  collapse_rows(columns = 1, valign = "top", latex_hline = "major")
```

```{r pvalues-table,echo=FALSE, cache=FALSE, warning=FALSE}

table_stats
```



